spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lojaonline
    username: postgres
    password: BlackOut1206@


  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create